from app.context.analytics.domain.events.dashboard_events import (
    DashboardCreated,
    DashboardCreatedFromTemplate,
    DashboardDeleted,
    DashboardShared,
    DashboardUnshared,
    DashboardUpdated,
    WidgetAdded,
    WidgetRemoved,
    WidgetReordered,
    WidgetUpdated,
)
from app.context.analytics.domain.events.report_events import (
    ReportCreated,
    ReportDeleted,
    ReportExported,
    ReportGenerated,
    ReportScheduled,
    ReportScheduleDeactivated,
    ReportShared,
    ReportUnshared,
    ReportUpdated,
)

__all__ = [
    "DashboardCreated",
    "DashboardCreatedFromTemplate",
    "DashboardDeleted",
    "DashboardShared",
    "DashboardUnshared",
    "DashboardUpdated",
    "WidgetAdded",
    "WidgetRemoved",
    "WidgetReordered",
    "WidgetUpdated",
    "ReportCreated",
    "ReportDeleted",
    "ReportExported",
    "ReportGenerated",
    "ReportScheduled",
    "ReportScheduleDeactivated",
    "ReportShared",
    "ReportUnshared",
    "ReportUpdated",
]
