"""add_reminder_window_hours_to_notification_preferences

Revision ID: b5a09105c9ac
Revises: b81b120e1d2c
Create Date: 2026-04-27 23:33:01.472902+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b5a09105c9ac'
down_revision: str | Sequence[str] | None = 'b81b120e1d2c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('reminder_window_hours', sa.Integer(), nullable=False, server_default='24'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'reminder_window_hours')
    # ### end Alembic commands ###
