"""workspace_initial

Revision ID: b0a97c3a34a4
Revises: b2c3d4e5f6a7
Create Date: 2026-04-24 21:03:11.490549+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b0a97c3a34a4'
down_revision: str | Sequence[str] | None = 'b2c3d4e5f6a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_invitations',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('token_value', sa.String(length=255), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_max_uses', sa.Integer(), nullable=True),
    sa.Column('token_used_count', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_invitations_role_id'), 'workspace_invitations', ['role_id'], unique=False)
    op.create_index(
        op.f('ix_workspace_invitations_workspace_id'),
        'workspace_invitations',
        ['workspace_id'],
        unique=False,
    )
    op.create_table('workspace_memberships',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_workspace_memberships_workspace_id'),
        'workspace_memberships',
        ['workspace_id'],
        unique=True,
    )
    op.create_table('workspace_roles',
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_roles_workspace_id'), 'workspace_roles', ['workspace_id'], unique=False)
    op.create_table('workspace_teams',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('member_ids', sa.JSON(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_teams_workspace_id'), 'workspace_teams', ['workspace_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('workspace_type', sa.String(length=30), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('parent_workspace_id', sa.Uuid(), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('owner_ids', sa.JSON(), nullable=True),
    sa.Column('pin_code_enabled', sa.Boolean(), nullable=False),
    sa.Column('password_enabled', sa.Boolean(), nullable=False),
    sa.Column('ip_allowlist', sa.JSON(), nullable=True),
    sa.Column('sso_mode', sa.String(length=20), nullable=False),
    sa.Column('require_2fa', sa.Boolean(), nullable=False),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=True),
    sa.Column('security_inherit_from_parent', sa.Boolean(), nullable=False),
    sa.Column('allow_invitation_links', sa.Boolean(), nullable=False),
    sa.Column('default_role', sa.String(length=50), nullable=False),
    sa.Column('require_approval', sa.Boolean(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('allowed_email_domains', sa.JSON(), nullable=True),
    sa.Column('auto_add_from_org', sa.Boolean(), nullable=False),
    sa.Column('membership_inherit_from_parent', sa.Boolean(), nullable=False),
    sa.Column('max_projects', sa.Integer(), nullable=True),
    sa.Column('ws_max_members', sa.Integer(), nullable=True),
    sa.Column('max_storage_bytes', sa.BigInteger(), nullable=True),
    sa.Column('max_file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('max_teams', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_organization_id'), 'workspaces', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workspaces_parent_workspace_id'), 'workspaces', ['parent_workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['workspace_memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_members_membership_id'), 'workspace_members', ['membership_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_role_id'), 'workspace_members', ['role_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_role_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_membership_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_workspaces_parent_workspace_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_organization_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_workspace_teams_workspace_id'), table_name='workspace_teams')
    op.drop_table('workspace_teams')
    op.drop_index(op.f('ix_workspace_roles_workspace_id'), table_name='workspace_roles')
    op.drop_table('workspace_roles')
    op.drop_index(op.f('ix_workspace_memberships_workspace_id'), table_name='workspace_memberships')
    op.drop_table('workspace_memberships')
    op.drop_index(op.f('ix_workspace_invitations_workspace_id'), table_name='workspace_invitations')
    op.drop_index(op.f('ix_workspace_invitations_role_id'), table_name='workspace_invitations')
    op.drop_table('workspace_invitations')
    # ### end Alembic commands ###
