"""add_membership_type_to_project_members

Revision ID: 467e66bf1128
Revises: 571364e59006
Create Date: 2026-04-26 11:08:35.227247+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467e66bf1128'
down_revision: Union[str, Sequence[str], None] = '571364e59006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('membership_type', sa.String(length=20), nullable=False, server_default='STANDARD'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_members', 'membership_type')
    # ### end Alembic commands ###
