"""profile_add_unique_constraints

Revision ID: 65b0fc8c5f54
Revises: a1b2c3d4e5f6
Create Date: 2026-04-22 21:30:21.415922+00:00

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '65b0fc8c5f54'
down_revision: str | Sequence[str] | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'uq_profile_notification_prefs_type',
        'profile_notification_preferences',
        ['profile_id', 'notification_type'],
    )
    op.create_unique_constraint(
        'uq_profile_pinned_items_target',
        'profile_pinned_items',
        ['profile_id', 'target_type', 'target_id'],
    )
    op.create_unique_constraint('uq_profile_social_links_platform', 'profile_social_links', ['profile_id', 'platform'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_profile_social_links_platform', 'profile_social_links', type_='unique')
    op.drop_constraint('uq_profile_pinned_items_target', 'profile_pinned_items', type_='unique')
    op.drop_constraint('uq_profile_notification_prefs_type', 'profile_notification_preferences', type_='unique')
    # ### end Alembic commands ###
