"""add_user_id_to_invitations

Revision ID: eee1867ad72f
Revises: d8f9a0b1c2e3
Create Date: 2026-04-26 14:02:08.818689+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'eee1867ad72f'
down_revision: str | Sequence[str] | None = 'd8f9a0b1c2e3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_invitations_user_id'), 'invitations', ['user_id'], unique=False)
    op.add_column('workspace_invitations', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_workspace_invitations_user_id'), 'workspace_invitations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_invitations_user_id'), table_name='workspace_invitations')
    op.drop_column('workspace_invitations', 'user_id')
    op.drop_index(op.f('ix_invitations_user_id'), table_name='invitations')
    op.drop_column('invitations', 'user_id')
    # ### end Alembic commands ###
