"""initial

Revision ID: fd6013d644ae
Revises: 
Create Date: 2026-04-22 11:18:21.882952+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6013d644ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('theme', sa.String(length=30), nullable=False),
    sa.Column('accent_color', sa.String(length=30), nullable=False),
    sa.Column('custom_theme_name', sa.String(length=100), nullable=True),
    sa.Column('custom_theme_colors', sa.JSON(), nullable=True),
    sa.Column('interface_density', sa.String(length=30), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('date_format', sa.String(length=30), nullable=False),
    sa.Column('time_format', sa.String(length=10), nullable=False),
    sa.Column('week_start_day', sa.String(length=10), nullable=False),
    sa.Column('start_page', sa.String(length=50), nullable=False),
    sa.Column('profile_visibility', sa.String(length=30), nullable=False),
    sa.Column('online_status_visibility', sa.String(length=30), nullable=False),
    sa.Column('activity_tracking_consent', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('profile_hotkey_configs',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('key_combination', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_hotkey_configs_profile_id'), 'profile_hotkey_configs', ['profile_id'], unique=False)
    op.create_table('profile_notification_preferences',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_notification_preferences_profile_id'), 'profile_notification_preferences', ['profile_id'], unique=False)
    op.create_table('profile_pinned_items',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_pinned_items_profile_id'), 'profile_pinned_items', ['profile_id'], unique=False)
    op.create_table('profile_sidebar_sections',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.String(length=100), nullable=False),
    sa.Column('is_collapsed', sa.Boolean(), nullable=False),
    sa.Column('item_ids', sa.JSON(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_sidebar_sections_profile_id'), 'profile_sidebar_sections', ['profile_id'], unique=False)
    op.create_table('profile_social_links',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_social_links_profile_id'), 'profile_social_links', ['profile_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('geo_country', sa.String(length=100), nullable=True),
    sa.Column('geo_city', sa.String(length=100), nullable=True),
    sa.Column('geo_latitude', sa.Float(), nullable=True),
    sa.Column('geo_longitude', sa.Float(), nullable=True),
    sa.Column('is_remember_me', sa.Boolean(), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('max_concurrent', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_auths',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_auths_email'), 'user_auths', ['email'], unique=False)
    op.create_index(op.f('ix_user_auths_user_id'), 'user_auths', ['user_id'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('auth_factors',
    sa.Column('user_auth_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('secret_value', sa.String(length=500), nullable=True),
    sa.Column('secret_method', sa.String(length=30), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_auth_id'], ['user_auths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_factors_user_auth_id'), 'auth_factors', ['user_auth_id'], unique=False)
    op.create_table('backup_codes',
    sa.Column('user_auth_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=500), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_auth_id'], ['user_auths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_codes_user_auth_id'), 'backup_codes', ['user_auth_id'], unique=False)
    op.create_table('email_verifications',
    sa.Column('user_auth_id', sa.Uuid(), nullable=False),
    sa.Column('verification_type', sa.String(length=50), nullable=False),
    sa.Column('token_value', sa.String(length=500), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_auth_id'], ['user_auths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_user_auth_id'), 'email_verifications', ['user_auth_id'], unique=False)
    op.create_table('login_attempts',
    sa.Column('user_auth_id', sa.Uuid(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('was_successful', sa.Boolean(), nullable=False),
    sa.Column('login_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_auth_id'], ['user_auths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_user_auth_id'), 'login_attempts', ['user_auth_id'], unique=False)
    op.create_table('oauth_links',
    sa.Column('user_auth_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_auth_id'], ['user_auths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_links_user_auth_id'), 'oauth_links', ['user_auth_id'], unique=False)
    op.create_table('trusted_devices',
    sa.Column('user_auth_id', sa.Uuid(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('trusted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_auth_id'], ['user_auths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trusted_devices_user_auth_id'), 'trusted_devices', ['user_auth_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trusted_devices_user_auth_id'), table_name='trusted_devices')
    op.drop_table('trusted_devices')
    op.drop_index(op.f('ix_oauth_links_user_auth_id'), table_name='oauth_links')
    op.drop_table('oauth_links')
    op.drop_index(op.f('ix_login_attempts_user_auth_id'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_email_verifications_user_auth_id'), table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index(op.f('ix_backup_codes_user_auth_id'), table_name='backup_codes')
    op.drop_table('backup_codes')
    op.drop_index(op.f('ix_auth_factors_user_auth_id'), table_name='auth_factors')
    op.drop_table('auth_factors')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_auths_user_id'), table_name='user_auths')
    op.drop_index(op.f('ix_user_auths_email'), table_name='user_auths')
    op.drop_table('user_auths')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_profile_social_links_profile_id'), table_name='profile_social_links')
    op.drop_table('profile_social_links')
    op.drop_index(op.f('ix_profile_sidebar_sections_profile_id'), table_name='profile_sidebar_sections')
    op.drop_table('profile_sidebar_sections')
    op.drop_index(op.f('ix_profile_pinned_items_profile_id'), table_name='profile_pinned_items')
    op.drop_table('profile_pinned_items')
    op.drop_index(op.f('ix_profile_notification_preferences_profile_id'), table_name='profile_notification_preferences')
    op.drop_table('profile_notification_preferences')
    op.drop_index(op.f('ix_profile_hotkey_configs_profile_id'), table_name='profile_hotkey_configs')
    op.drop_table('profile_hotkey_configs')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_table('roles')
    # ### end Alembic commands ###
