"""rename_icon_url_to_icon

Revision ID: b81b120e1d2c
Revises: ca3954d9ff08
Create Date: 2026-04-27 20:30:32.105564+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b81b120e1d2c'
down_revision: str | Sequence[str] | None = 'ca3954d9ff08'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('pers_icon', sa.String(length=2048), nullable=True))
    op.drop_column('organizations', 'pers_icon_url')
    op.add_column('teams', sa.Column('icon', sa.String(length=2048), nullable=True))
    op.drop_column('teams', 'icon_url')
    op.add_column('workspace_teams', sa.Column('icon', sa.Text(), nullable=True))
    op.drop_column('workspace_teams', 'icon_url')
    op.add_column('workspaces', sa.Column('icon', sa.Text(), nullable=True))
    op.drop_column('workspaces', 'icon_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('icon_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('workspaces', 'icon')
    op.add_column('workspace_teams', sa.Column('icon_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('workspace_teams', 'icon')
    op.add_column('teams', sa.Column('icon_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.drop_column('teams', 'icon')
    op.add_column('organizations', sa.Column('pers_icon_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.drop_column('organizations', 'pers_icon')
    # ### end Alembic commands ###
