"""organization_initial

Revision ID: 736039843518
Revises: 65b0fc8c5f54
Create Date: 2026-04-24 14:02:19.795672+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '736039843518'
down_revision: str | Sequence[str] | None = '65b0fc8c5f54'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pers_color_hex', sa.String(length=7), nullable=True),
    sa.Column('pers_icon_url', sa.String(length=2048), nullable=True),
    sa.Column('pers_display_name', sa.String(length=255), nullable=True),
    sa.Column('pers_custom_domain', sa.String(length=255), nullable=True),
    sa.Column('pers_branding_logo_url', sa.String(length=2048), nullable=True),
    sa.Column('pers_branding_favicon_url', sa.String(length=2048), nullable=True),
    sa.Column('pers_branding_custom_css', sa.Text(), nullable=True),
    sa.Column('pers_branding_login_message', sa.Text(), nullable=True),
    sa.Column('sp_require_2fa', sa.Boolean(), nullable=False),
    sa.Column('sp_password_min_length', sa.Integer(), nullable=False),
    sa.Column('sp_session_timeout_minutes', sa.Integer(), nullable=True),
    sa.Column('sp_ip_allowlist', sa.JSON(), nullable=True),
    sa.Column('sp_domain_restrictions', sa.JSON(), nullable=True),
    sa.Column('sp_require_email_verification', sa.Boolean(), nullable=False),
    sa.Column('mp_allow_invitation_links', sa.Boolean(), nullable=False),
    sa.Column('mp_default_role', sa.String(length=100), nullable=False),
    sa.Column('mp_require_approval', sa.Boolean(), nullable=False),
    sa.Column('mp_max_members', sa.Integer(), nullable=True),
    sa.Column('mp_allowed_email_domains', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_org_id'), 'departments', ['org_id'], unique=False)
    op.create_index(op.f('ix_departments_parent_id'), 'departments', ['parent_id'], unique=False)
    op.create_table('invitations',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('link_value', sa.String(length=512), nullable=True),
    sa.Column('link_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('link_max_uses', sa.Integer(), nullable=True),
    sa.Column('link_used_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_value')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_org_id'), 'invitations', ['org_id'], unique=False)
    op.create_table('org_memberships',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_memberships_org_id'), 'org_memberships', ['org_id'], unique=True)
    op.create_table('org_owners',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'user_id')
    )
    op.create_table('org_roles',
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_roles_name'), 'org_roles', ['name'], unique=False)
    op.create_index(op.f('ix_org_roles_org_id'), 'org_roles', ['org_id'], unique=False)
    op.create_table('sso_integrations',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=500), nullable=False),
    sa.Column('sso_url', sa.String(length=2048), nullable=False),
    sa.Column('certificate', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('group_mapping', sa.JSON(), nullable=True),
    sa.Column('attribute_mapping', sa.JSON(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'provider', name='uq_sso_integrations_org_provider')
    )
    op.create_index(op.f('ix_sso_integrations_org_id'), 'sso_integrations', ['org_id'], unique=False)
    op.create_table('storage_integrations',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('sc_provider', sa.String(length=50), nullable=False),
    sa.Column('sc_endpoint', sa.String(length=2048), nullable=True),
    sa.Column('sc_bucket', sa.String(length=255), nullable=False),
    sa.Column('sc_region', sa.String(length=100), nullable=False),
    sa.Column('sc_access_key', sa.Text(), nullable=False),
    sa.Column('sq_max_bytes', sa.Integer(), nullable=False),
    sa.Column('sq_used_bytes', sa.Integer(), nullable=False),
    sa.Column('sq_max_file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('sq_allowed_extensions', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_integrations_org_id'), 'storage_integrations', ['org_id'], unique=True)
    op.create_table('teams',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('icon_url', sa.String(length=2048), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_org_id'), 'teams', ['org_id'], unique=False)
    op.create_table('department_members',
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('department_id', 'user_id')
    )
    op.create_table('org_members',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['org_memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_members_membership_id'), 'org_members', ['membership_id'], unique=False)
    op.create_index(op.f('ix_org_members_role_id'), 'org_members', ['role_id'], unique=False)
    op.create_index(op.f('ix_org_members_user_id'), 'org_members', ['user_id'], unique=False)
    op.create_table('team_members',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_members')
    op.drop_index(op.f('ix_org_members_user_id'), table_name='org_members')
    op.drop_index(op.f('ix_org_members_role_id'), table_name='org_members')
    op.drop_index(op.f('ix_org_members_membership_id'), table_name='org_members')
    op.drop_table('org_members')
    op.drop_table('department_members')
    op.drop_index(op.f('ix_teams_org_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_storage_integrations_org_id'), table_name='storage_integrations')
    op.drop_table('storage_integrations')
    op.drop_index(op.f('ix_sso_integrations_org_id'), table_name='sso_integrations')
    op.drop_table('sso_integrations')
    op.drop_index(op.f('ix_org_roles_org_id'), table_name='org_roles')
    op.drop_index(op.f('ix_org_roles_name'), table_name='org_roles')
    op.drop_table('org_roles')
    op.drop_table('org_owners')
    op.drop_index(op.f('ix_org_memberships_org_id'), table_name='org_memberships')
    op.drop_table('org_memberships')
    op.drop_index(op.f('ix_invitations_org_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_departments_parent_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_org_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_table('organizations')
    # ### end Alembic commands ###
